# -*- coding: utf-8 -*-
"""app.py

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1Mz8r6DENzWWnzAmFQwZJjQW0ky4dHFzv
"""

import pandas as pd
import numpy as np

class CampaignOptimizer:
    def __init__(self):
        # 1. DỮ LIỆU TÍCH HỢP SẴN (Hardcoded Data from Excel)
        # Giúp app chạy độc lập không cần file Excel
        self.tiers = ['1K to <10K', '10K to <50K', '50K to <150K', '150K to < 500K', '500K and up']

        self.raw_data = {
            'Instagram': {
                'Reach': [3258, 21417, 87664, 264830, 2206768],
                'Cost_Post': [268.22, 443.84, 1140.22, 3315.63, 11059.85],
                'Cost_Story': [160.24, 301.84, 783.57, 2260.49, 7525.33],
                'Supply': [246209, 68181, 20454, 9461, 5305],
                # Tỉ lệ Reach thực tế ước tính (Nano cao, Mega thấp)
                'Reach_Rate': [0.25, 0.15, 0.10, 0.05, 0.03]
            },
            'Twitter': {
                'Reach': [4952, 21765, 85206, 266771, 1838483],
                'Cost_Post': [0, 0, 0, 0, 0], # Twitter dùng giá Tweet
                'Cost_Tweet': [131.34, 207.33, 504.2, 1490.99, 4656.37],
                'Supply': [2907, 2062, 896, 552, 279],
                'Reach_Rate': [0.15, 0.10, 0.08, 0.05, 0.02]
            },
            'TikTok': {
                'Reach': [4373, 25013, 90230, 275338, 2087679],
                'Cost_Post': [184.57, 335.92, 697.04, 1806.5, 5757.25],
                'Cost_Story': [0, 0, 0, 0, 0],
                'Supply': [6233, 7449, 4757, 3746, 2601],
                'Reach_Rate': [0.50, 0.30, 0.20, 0.10, 0.05] # TikTok viral cao
            }
        }
        self.df_model = self._build_model()

    def _build_model(self):
        """Chuyển đổi dữ liệu thô thành DataFrame để tính toán"""
        data_list = []
        for platform, data in self.raw_data.items():
            for i, tier in enumerate(self.tiers):
                # Xác định chi phí chính (Tweet cho Twitter, Post cho others)
                cost_main = data.get('Cost_Tweet', data.get('Cost_Post'))[i]

                row = {
                    'Platform': platform,
                    'Tier': tier,
                    'Followers': data['Reach'][i],
                    'Reach_Rate': data['Reach_Rate'][i],
                    'True_Reach': data['Reach'][i] * data['Reach_Rate'][i], # Quan trọng: Reach thực tế
                    'Unit_Price': cost_main,
                    'Supply': int(data['Supply'][i])
                }
                data_list.append(row)
        return pd.DataFrame(data_list)

    def optimize(self, budget, strategy="mass_seeding", content_per_kol=1):
        """
        Hàm tối ưu hóa chính.
        Args:
            budget (float): Ngân sách tổng.
            strategy (str):
                - "mass_seeding": Chỉ chọn nhóm Nano/Micro (1K-50K).
                - "max_reach": Tự do chọn kênh rẻ nhất (thường là Tier to).
            content_per_kol (int): Số bài đăng mỗi KOL phải làm.
        """
        df = self.df_model.copy()

        # 1. Lọc theo chiến thuật (Strategy Filter)
        if strategy == "mass_seeding":
            target_tiers = ['1K to <10K', '10K to <50K']
            df = df[df['Tier'].isin(target_tiers)]
            print(f"\n--- STRATEGY: MASS SEEDING (Focus on Tier 1K-50K) ---")
        else:
            print(f"\n--- STRATEGY: MAX REACH (Freedom to pick any Tier) ---")

        # 2. Tính toán chi phí thực tế cho mỗi KOL
        df['Pack_Cost'] = df['Unit_Price'] * content_per_kol

        # 3. Tính ROI (Return on Investment)
        # ROI = True Reach / Cost => Càng cao càng tốt
        df['ROI'] = df['True_Reach'] / df['Pack_Cost']

        # Sắp xếp để mua kênh hiệu quả nhất trước
        df = df.sort_values(by='ROI', ascending=False)

        # 4. Phân bổ ngân sách (Greedy Allocation)
        allocations = []
        remaining_budget = budget

        for index, row in df.iterrows():
            if remaining_budget <= 0:
                allocations.append(0)
                continue

            cost = row['Pack_Cost']
            supply = row['Supply']

            # Có thể mua bao nhiêu người? (Min của Khả năng chi trả và Nguồn cung)
            if cost > 0:
                max_affordable = int(remaining_budget // cost)
                count = min(max_affordable, supply)
            else:
                count = 0

            allocations.append(count)
            remaining_budget -= count * cost

        # 5. Tổng hợp kết quả
        df['Participants'] = allocations
        df['Total_Cost'] = df['Participants'] * df['Pack_Cost']
        df['Total_True_Reach'] = df['Participants'] * df['True_Reach']
        df['Total_Content'] = df['Participants'] * content_per_kol

        # Lọc ra những dòng có chọn (Participants > 0)
        result = df[df['Participants'] > 0].copy()

        return result, remaining_budget

    def print_plan(self, result_df, remaining_budget):
        if result_df.empty:
            print("Ngân sách quá thấp không thể thuê ai!")
            return

        print(f"{'Platform':<10} | {'Tier':<15} | {'PPL':<5} | {'Content':<7} | {'Cost ($)':<12} | {'True Reach':<12}")
        print("-" * 80)

        for _, row in result_df.iterrows():
            print(f"{row['Platform']:<10} | {row['Tier']:<15} | {row['Participants']:<5} | {row['Total_Content']:<7} | {row['Total_Cost']:<12,.2f} | {row['Total_True_Reach']:<12,.0f}")

        print("-" * 80)
        total_spend = result_df['Total_Cost'].sum()
        total_reach = result_df['Total_True_Reach'].sum()
        total_ppl = result_df['Participants'].sum()

        print(f"SUMMARY:")
        print(f"  > Total Participants: {total_ppl} KOLs")
        print(f"  > Total Spend:        ${total_spend:,.2f} (Remaining: ${remaining_budget:,.2f})")
        print(f"  > Est. True Reach:    {total_reach:,.0f} unique views")
        print("=" * 80)

# --- MAIN EXECUTION ---
if __name__ == "__main__":
    app = CampaignOptimizer()

    # CASE 1: Ngân sách $22K, Chiến thuật Mass Seeding (1K-50K)
    print("INPUT: Budget = $22,000 | Strategy = Mass Seeding (1K-50K)")
    plan_seeding, rem_seeding = app.optimize(budget=22000, strategy="mass_seeding", content_per_kol=1)
    app.print_plan(plan_seeding, rem_seeding)

    # CASE 2: Ngân sách $100K, Chiến thuật Max Reach (Thả cửa)
    print("\n\nINPUT: Budget = $100,000 | Strategy = Max Reach (All Tiers)")
    plan_max, rem_max = app.optimize(budget=100000, strategy="max_reach", content_per_kol=1)
    app.print_plan(plan_max, rem_max)